M48
; DRILL file {KiCad 7.0.5} date Sun Jun 25 23:49:41 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-06-25T23:49:41-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C6.400
%
G90
G05
T1
X115.215Y-57.93
X120.065Y-57.93
T2
X114.915Y-54.9
X120.365Y-54.9
T3
X86.0Y-47.0
X86.0Y-110.0
X149.0Y-47.0
X149.0Y-110.0
T4
X96.8Y-57.9
T0
M30
